### ISSUE TITLE
Is the logic correct?

### ISSUE THREAD

**Issue by kafka399** [kamicollo/home-court-advantage#1]
Hi, 
I was trying to understand `is_home` logic as it is not obvious looking into the dataset itself. ATM, the code checks which team id is higher. If it is intentionally, would be interesting to know the logic behind:

https://github.com/kamicollo/home-court-advantage/blob/7daa05a4825e157b2c06925c3946af1ffa62a1e2/modelling/data_utils.py#L27

**Comment by kamicollo** [comment]
Hi! 

You're right, it's not a super intuitive piece of code. It stems from the fact that when I model the specification that uses pairwise strengths, a 2-team pair needs to be encoded only once (i.e. when team X plays team Y at team X arena it's the same pair as when they play at the team Y arena). So when encoding pairs, I chose to set it up so that the larger ID always comes first:

```python
def helper_(x):
            return (max(x['home-team-id'], x['away-team-id']), min(x['home-team-id'], x['away-team-id']))
        all_games['pair_id'] = all_games.apply(helper_, axis=1)
```

However, when it comes to modeling, I need to make sure I am using the right sign for scores. The way this works is that this piece of code ensures that `score_diff` is always for the team that is encoded first in the pair. 
```python
        all_games['is_home'] = (all_games['home-team-id'] > all_games['away-team-id']) * 1
        all_games['is_home'] = all_games['is_home'].apply(lambda x: x if x == 1 else -1)
        all_games['score_diff'] = (all_games['home-points'] - all_games['away-points']) * all_games['is_home']
```
I.e., if team X plays team Y and wins by 10 points, then the final data, no matter where they play, will look like this:
``` 
     pair_id | score_diff
     (X,Y)       +10
```

Arguably, a slightly easier way to do it is how I deal with these sign reversals in my follow-up [blog post](https://github.com/kamicollo/blog-posts/blob/main/home-court-advantage/notebook.ipynb):

```python
with sq.connect(DB_PATH_2023) as conn:
    sql = """
    SELECT `home-points`, `away-points`, `home-points` - `away-points` as `score_diff`,
    ht.name as `home-team`, at.name as `away-team`, 
    `start-year` as season, `date`
    FROM games
    JOIN seasons ON games.season_id = seasons.id
    JOIN teams ht ON `home-team-id` = ht.id
    JOIN teams at ON `away-team-id` = at.id
    WHERE `regular` = 1 AND `start-year` > '1994'
    ORDER BY `game-id`
    ;
    """
    all_games = pd.read_sql_query(sql, conn)

def helper_(x):
    return (max(x['home-team'], x['away-team']), min(x['home-team'], x['away-team']))
all_games['pair'] = all_games.apply(helper_, axis=1)
all_games['pair_is_reversed'] = all_games.apply(
    lambda x: 1 if x['pair'][0] == x['home-team'] else -1, 
    axis=1
)
```
Instead of reversing the score difference, I just have a variable that I can use to know if the pair is reversed:

```python
S = α[season_idx, pairs_idx] * strengths_reversed + β[home_team_idx]
pm.Normal('scores', mu=S, sigma=ε[season_idx], observed=score_diffs)
```

**Comment by kafka399** [comment]
Thanks for clarification!
